synopsis: waterfall-cad wrapper

license: LGPL-2.1-only

dependencies:
  - base
  - waterfall-cad >= 0.6.2.1
  - linear
  - process
  - lens
  - directory
  - filepath
  - transformers
  - opencascade-hs
  - inline-c-cpp
  - inline-c
  - resourcet
  - containers
  - template-haskell
  - StateVar
  - text
  - random
  - these

pkg-config-dependencies:
  - qhull_r

default-extensions:
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - FlexibleContexts
  - FlexibleInstances
  - ForeignFunctionInterface
  - MultiParamTypeClasses
  - OverloadedStrings
  - QuasiQuotes
  - ScopedTypeVariables
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - ViewPatterns

library:
  source-dirs:
    - lib
